import dotenv from "dotenv";
import path from "path";
import { sendTicketEmail } from "./src/utils/mailer.js";

dotenv.config();

// ==========================================
// 1. SET YOUR TEST RECIPIENT EMAIL HERE 
// ==========================================
const TEST_EMAIL = "your-test-email@gmail.com"; 

async function runTest() {
  console.log(`Starting email test to: ${TEST_EMAIL}...`);

  const mockData = {
    agencyName: "ProfitMate Travel Agency",
    logoUrl: "", // Optional remote URL
    primaryColor: "#0ea5e9", // A nice soft blue
    passengerName: "John Doe",
    messageBody: "This is a test run of our brand new ProfitMate dynamic ticket emailing system! \nSafe travels.",
    footerText: "Please verify flight times. This document is generated by ProfitMate."
  };

  // We are grabbing the existing PDF from your uploads directory
  const existingPdf = path.resolve("uploads", "rendered", "1771172827804_YWXYZR_Passenger.pdf");

  try {
    const result = await sendTicketEmail(
      TEST_EMAIL,
      "Your upcoming trip itinerary from ProfitMate",
      mockData,
      existingPdf,
      "ETicket_JohnDoe.pdf" // Dynamic name testing
    );
    console.log("TEST SUCCESSFUL! 🚀");
    console.log("Check your inbox (and spam folder) for the test email.");
  } catch (error) {
    console.error("TEST FAILED ❌");
    console.error(error);
  }

  process.exit(0);
}

runTest();
