
 ####

 POST  http://localhost:4000/api/auth/login
 Content-Type: application/json

 {
    "email" : "superadmin@example.com",
    "password" : "SuperStrongPassword123!"
 }


#  {
#     "email" : "nurtrv002@example.com",
#     "password" : "12345678"
#  }

###
 POST  http://localhost:4000/api/records
  Content-Type: application/json
  Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YjA0MWYzYmU2NzZlMjhhNDQzNmQzOSIsInJvbGUiOiJBR0VOQ1lfQURNSU4iLCJhZ2VuY3kiOiI2OGIwMmZhMDY3YzE4ZDc2MTkzZTdiN2QiLCJpYXQiOjE3NTYzODE4NTUsImV4cCI6MTc1Njk4NjY1NX0.nvNnauQMaj4KkpdPJXXQ3jp_xfi27pX4RN43DHmuLI4

{
   "customerName": "mmm", 
   "typeOfService": "flight",
   "sellingPrice": 200,
   "buyingPrice": 1000,
   "expenses": 50,
   "notes": " afro record",
   "agency": "68b036b767c18d76193e7b91"
 }


###
GET  http://localhost:4000/api/reports/summary?day=2025-08-28
 Content-Type: application/json
  Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YjA0MWYzYmU2NzZlMjhhNDQzNmQzOSIsInJvbGUiOiJBR0VOQ1lfQURNSU4iLCJhZ2VuY3kiOiI2OGIwMmZhMDY3YzE4ZDc2MTkzZTdiN2QiLCJpYXQiOjE3NTYzODE4NTUsImV4cCI6MTc1Njk4NjY1NX0.nvNnauQMaj4KkpdPJXXQ3jp_xfi27pX4RN43DHmuLI4

###
 GET  http://localhost:4000/api/reports/summary?month=2025-08
 Content-Type: application/json
  Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YjA0MWYzYmU2NzZlMjhhNDQzNmQzOSIsInJvbGUiOiJBR0VOQ1lfQURNSU4iLCJhZ2VuY3kiOiI2OGIwMmZhMDY3YzE4ZDc2MTkzZTdiN2QiLCJpYXQiOjE3NTYzODE4NTUsImV4cCI6MTc1Njk4NjY1NX0.nvNnauQMaj4KkpdPJXXQ3jp_xfi27pX4RN43DHmuLI4
###
GET http://localhost:4000/api/reports/summary?from=2025-07-01&to=2025-07-15
 Content-Type: application/json
  Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YjA0MWYzYmU2NzZlMjhhNDQzNmQzOSIsInJvbGUiOiJBR0VOQ1lfQURNSU4iLCJhZ2VuY3kiOiI2OGIwMmZhMDY3YzE4ZDc2MTkzZTdiN2QiLCJpYXQiOjE3NTYzODE4NTUsImV4cCI6MTc1Njk4NjY1NX0.nvNnauQMaj4KkpdPJXXQ3jp_xfi27pX4RN43DHmuLI4


###
GET http://localhost:4000/api/records?day=2025-08-28
Content-Type: application/json
  Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YjA0MWYzYmU2NzZlMjhhNDQzNmQzOSIsInJvbGUiOiJBR0VOQ1lfQURNSU4iLCJhZ2VuY3kiOiI2OGIwMmZhMDY3YzE4ZDc2MTkzZTdiN2QiLCJpYXQiOjE3NTYzODE4NTUsImV4cCI6MTc1Njk4NjY1NX0.nvNnauQMaj4KkpdPJXXQ3jp_xfi27pX4RN43DHmuLI4

###
GET http://localhost:4000/api/records?month=2025-08
Content-Type: application/json
  Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YjA0MWYzYmU2NzZlMjhhNDQzNmQzOSIsInJvbGUiOiJBR0VOQ1lfQURNSU4iLCJhZ2VuY3kiOiI2OGIwMmZhMDY3YzE4ZDc2MTkzZTdiN2QiLCJpYXQiOjE3NTYzODE4NTUsImV4cCI6MTc1Njk4NjY1NX0.nvNnauQMaj4KkpdPJXXQ3jp_xfi27pX4RN43DHmuLI4

###
GET http://localhost:4000/api/records?from=2025-07-01&to=2025-07-31
Content-Type: application/json
  Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YjA0MWYzYmU2NzZlMjhhNDQzNmQzOSIsInJvbGUiOiJBR0VOQ1lfQURNSU4iLCJhZ2VuY3kiOiI2OGIwMmZhMDY3YzE4ZDc2MTkzZTdiN2QiLCJpYXQiOjE3NTYzODE4NTUsImV4cCI6MTc1Njk4NjY1NX0.nvNnauQMaj4KkpdPJXXQ3jp_xfi27pX4RN43DHmuLI4
