export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  AGENCY_ADMIN: 'AGENCY_ADMIN',
  PARTNER: 'PARTNER',
  ACCOUNTANT: 'ACCOUNTANT',
};
export const ROLE_HIERARCHY = {
  SUPER_ADMIN: 3,
  AGENCY_ADMIN: 2,
  PARTNER: 1,
  ACCOUNTANT: 1,
};
