import mongoose from "mongoose";

const TicketTemplateSchema = new mongoose.Schema(
  {
    agencyId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Agency",
      required: true,
      index: true,
      unique: true,
    },

    brand: {
      agencyName: { type: String, default: "" },
      slogan: { type: String, default: "" },
      phone: { type: String, default: "" },
      email: { type: String, default: "" },
      address: { type: String, default: "" },
      logoUrl: { type: String, default: "" }, // e.g: /uploads/agencies/xxx.png
    },

    theme: {
      primaryColor: { type: String, default: "#0ea5e9" },
      secondaryColor: { type: String, default: "#111827" },
      accentColor: { type: String, default: "#22c55e" },
      fontFamily: { type: String, default: "Inter, Arial, sans-serif" },
      paper: { type: String, enum: ["A4", "LETTER"], default: "A4" },
    },

    show: {
      showAgencyHeader: { type: Boolean, default: true },
      showPassengerList: { type: Boolean, default: true },
      showETickets: { type: Boolean, default: true },
      showPNR: { type: Boolean, default: true },
      showTerminals: { type: Boolean, default: true },
      showCabin: { type: Boolean, default: true },
      showNotes: { type: Boolean, default: true },
    },

    footer: {
      disclaimer: {
        type: String,
        default:
          "Please verify flight times prior to departure. This document is generated by your travel agency system.",
      },
    },
  },
  { timestamps: true }
);

export default mongoose.model("TicketTemplate", TicketTemplateSchema);
